explore_maps = {
    # Africa
    "botswana",
    "kenya",
    "lesotho",
    "senegal",
    "south-africa",
    # Asia
    "bangladesh",
    "cambodia",
    "india",
    "indonesia",
    "israel",
    "japan",
    "malaysia",
    "mongolia",
    "philippines",
    "russia",
    "singapore",
    "south-korea",
    "taiwan",
    "thailand",
    # Europe
    "belgium",
    "bulgaria",
    "croatia",
    "czech-republic",
    "denmark",
    "estonia",
    "finland",
    "france",
    "germany",
    "greece",
    "hungary",
    "iceland",
    "ireland",
    "italy",
    "latvia",
    "lithuania",
    "luxembourg",
    "netherlands",
    "norway",
    "poland",
    "portugal",
    "romania",
    "serbia",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
    "switzerland",
    "turkey",
    "ukraine",
    "uk",
    # North America
    "canada",
    "greenland",
    "guatemala",
    "mexico",
    "usa",
    # Oceania
    "australia",
    "new-zealand",
    # South America
    "argentina",
    "bolivia",
    "brazil",
    "chile",
    "colombia",
    "ecuador",
    "peru",
    "uruguay",
}
